# Site settings
title: Leedo - 개발자 이도원
url: https://leedo1982.github.io
baseurl: ""
description: 
    Leedo_이도원 블로그

# My information
email: domo18@gmail.com
author: Leedowon
profile: 리부트 
github_username: leedo1982
comment-support: utterances
disqus_shortname: leedo1982



# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: leedo1982
  shortname: leedo1982

google_analytics:
  ua: UA-116747029-1

google_adsense:
  client: ca-pub-3675948545737694

utterances:
  repo: leedo1982/leedo1982.github.io
  issue-term: pathname
  label: Comment
  branch: master

blame: "https://github.com/leedo1982/leedo1982.github.io/blame/master/_wiki"
edit: "https://github.com/leedo1982/leedo1982.github.io/edit/master/_wiki"
issue: "https://github.com/leedo1982/leedo1982.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
