'2019':
    - {fileName: 2019_BOOK_LIST}
book:
    - {fileName: 2019_BOOK_LIST}
    - {fileName: PRACTICAL_VIM}
    - {fileName: PRO_GIT}
    - {fileName: THE_NATURE_OF_SOFRWARE_DEVELOPEMENT}
DDD:
    - {fileName: DDD_Entity}
eventsourcing:
    - {fileName: EVENT-SOURCING}
how-to:
    - {fileName: how-to}
sql:
    - {fileName: REAL_MYSQL}
db:
    - {fileName: REAL_MYSQL}
spring:
    - {fileName: Redis}
redis:
    - {fileName: Redis}
failover:
    - {fileName: RollbackException}
