'2019':
    - {fileName: 2019_BOOK_LIST}
book:
    - {fileName: 2019_BOOK_LIST}
    - {fileName: THE_NATURE_OF_SOFRWARE_DEVELOPEMENT}
eventsourcing:
    - {fileName: EVENT-SOURCING}
how-to:
    - {fileName: how-to}
spring:
    - {fileName: Redis}
redis:
    - {fileName: Redis}
failover:
    - {fileName: RollbackException}
